services:
  - type: web
    name: credit-analysis-app
    runtime: docker
    dockerContext: ./web_app
    dockerfilePath: ./web_app/Dockerfile
    plan: free
    region: oregon
    branch: main
    numInstances: 1
    healthCheckPath: /_stcore/health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
